concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner-localhost"
  url = "http://localhost-gitlab/"
  token = "XXXXXXXXXXXXXXXXXXXXXX"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mode = "localhost-gitlab-configs_default"

# You need to set "network_mode" according to what is shown on docker-compose up (it's a name of the current directory + _default :
# It's needed so a domain name of the gitlab container resolved correctly within gitlab-job.
# So you can avoid:
# fatal: unable to access 'http://localhost-gitlab/nsnegin/wlan-portal.git/': Could not resolve host: localhost-gitlab
# ERROR: Job failed: exit code 1
#
# nikolai@SPBNB-PRC4370:~/docker-compose-manifests/localhost-gitlab-configs$ docker-compose up -d
# Creating network "localhost-gitlab-configs_default" with the default driver
# Creating localhost-gitlab-configs_localhost-runner_1 ... done
# Creating localhost-gitlab-configs_localhost-gitlab_1 ... done
# nikolai@SPBNB-PRC4370:~/docker-compose-manifests/localhost-gitlab-configs$
